main: 
	gcc main.c -o bin && ./bin

binary_search_array: 
	gcc binary_search_array.c -o bin && ./bin

insertion_sort: 
	gcc insertion_sort.c -o bin && ./bin

selection_sort: 
	gcc selection_sort.c -o bin && ./bin

bubble_sort: 
	gcc bubble_sort.c -o bin && ./bin